library(jsonlite)

all_projections <- function() {
  
#steamer  
steamer_api <- "https://www.fangraphs.com/api/projections?type=steamer&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=standard&fantasypreset=dashboard
"
data <- jsonlite::fromJSON(steamer_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "Steamer"
         )

#ZiPS  
zips_api <- "https://www.fangraphs.com/api/projections?type=zips&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data2 <- jsonlite::fromJSON(zips_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "ZiPS"
         )

#thebat  
thebat_api <- "https://www.fangraphs.com/api/projections?type=thebat&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data3 <- jsonlite::fromJSON(thebat_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "THE BAT"
        )

#thebatx  
thebatx_api <- "https://www.fangraphs.com/api/projections?type=thebatx&statas=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data4 <- jsonlite::fromJSON(thebatx_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "THE BATX"
  )

#ZiPS DC  
zipsdc_api <- "https://www.fangraphs.com/api/projections?type=zipsdc&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data5 <- jsonlite::fromJSON(zipsdc_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "ZiPS DC"
  )


#depth charts  
depthcharts_api <- "https://www.fangraphs.com/api/projections?type=fangraphsdc&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data6 <- jsonlite::fromJSON(depthcharts_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "Depth Charts"
  )


#ATC  
atc_api <- "https://www.fangraphs.com/api/projections?type=atc&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data7 <- jsonlite::fromJSON(atc_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "ATC"
  )


#OOPSY  
oopsy_api <- "https://www.fangraphs.com/api/projections?type=oopsy&stats=bat&pos=all&team=0&players=0&lg=all&z=1739763686&pageitems=30&statgroup=fantasy&fantasypreset=dashboard"

data8 <- jsonlite::fromJSON(oopsy_api) |>
  mutate(season = 2025) |>
  select(season,
         playerid = playerids,
         name = PlayerName,
         team = Team,
         team_name = ShortName,
         G,
         AB,
         PA,
         H,
         X1B = `1B`,
         X2B = `2B`,
         X3B = `3B`,
         HR,
         R,
         RBI,
         BB,
         IBB,
         SO,
         HBP,
         SF,
         SH,
         SB,
         CS,
         AVG,
         OBP,
         SLG,
         OPS,
         wOBA, 
         BB_pct = `BB%`,
         K_pct = `K%`,
         BB_K = `BB/K`,
         ISO,
         BABIP,
         Spd,
         BaseRunning,
         wRAA,
         wRC,
         wRC_plus = `wRC+`,
         WAR) |>
  mutate(OPS = round(OPS,3),
         AVG = round(AVG,3),
         SLG = round(SLG,3),
         OBP = round(OBP,3),
         ISO = round(ISO,3),
         BABIP = round(BABIP,3),
         Spd = round(Spd,3),
         BB_pct = round(BB_pct,3),
         K_pct = round(K_pct,3),
         BB_K = round(BB_K,3),
         wRC = round(wRC),
         wRC_plus = round(wRC_plus),
         WAR = round(WAR,1),
         Source = "OOPSY"
  )

sources <- bind_rows(data, data2, data3, data4, data5, data6, data7, data8)

sources
}

projections <- all_projections()

write.csv(projections, "source_projections.csv", row.names = FALSE)
